### ISSUE TITLE
Unable to harvest earth fruits after harvesting carrot, red beet or parsnip.

### ISSUE THREAD

**Issue by DeeDeeRanged** [tn4799/DynamicMissionVehicles#11] opened 2023-12-08 15:32 UTC
I have been using your mod fine for the potatoes and sugarbeet which is great but unable to harvest any of the new fruits from the Premium DLC.
Downloaded the latest one from modhub.

**Comment by tn4799** [comment] 2023-12-08 15:46
what map are you playing on?

And please also attach your log.txt

**Comment by DeeDeeRanged** [comment] 2023-12-08 19:24
Map is Zielonka
I the mean time had a crash with the game so got the copy from savegameBaxkup. 
Started also some digging and had an idea it was colliding/issues with another mod (not from modhub) and I was right but because of the crash.
 I don't have the mod anymore but installed from some other website.
In anycase it works now what is awesome. For just the vegetables I use/used the mod FS22_Grimme_PremiunDLC works great as a veggie harvester no need for a haulm topper doesn't do potato or sugarbeet though.
In any cas I attach the log file
[log.txt](https://github.com/tn4799/DynamicMissionVehicles/files/13620135/log.txt)

**Comment by DeeDeeRanged** [comment] 2023-12-08 20:32
I spoke to soon the keiler2 is doing just potatoes again and does not recognize redbeet.
Attached 3 more log files
[log1.txt](https://github.com/tn4799/DynamicMissionVehicles/files/13620694/log1.txt)
[log2.txt](https://github.com/tn4799/DynamicMissionVehicles/files/13620697/log2.txt)
[log3.txt](https://github.com/tn4799/DynamicMissionVehicles/files/13620700/log3.txt)

**Comment by tn4799** [comment] 2023-12-09 12:50
Thanks for reporting the bug. I'm working on a hotfix, but I dont know how long it will take

**Comment by DeeDeeRanged** [comment] 2023-12-09 21:55
Thanks anyway, will just wait patiently for the the fix.

**Comment by DeeDeeRanged** [comment] 2023-12-17 17:24
Funny thing is that one moment it is working as intended for all fruits and the next time starting up the game it reverts back to only doing potatoes and sugarbeets.

**Comment by tn4799** [comment] 2023-12-17 17:38
I already found the bug and fixed it.
The update is already submitted to GIANTS to be tested for a modhub release. I have no control anymore on when the update will drop.

The problem is, that you cannot harvest the new fruits once you harvested potatos or sugar beet. A workaround till the update should be reloading the game or resetting the vehicle

**Comment by DeeDeeRanged** [comment] 2023-12-18 11:31
Just a question out of curiosity. Do you need to have DynamicMissionVehicles installed or can you use the Multi Fruit Pack on its own?

**Comment by tn4799** [comment] 2023-12-18 17:45
The harvester Pack works completly on its own.

**Comment by ionut-girla** [comment] 2024-01-04 16:40
Hello, 

Same issue when trying to harvest sugar beet after carrots on Haut-Beyleron

**Comment by tn4799** [comment] 2024-01-04 17:19
> Hello,
> 
> Same issue when trying to harvest sugar beet after carrots on Haut-Beyleron

The problem is not map related. Its an error in the script. 
An update was already submitted weeks ago to the modhub. It will be fixed once the update arrives. 

Till then you can reset the vehicle or reload the savegame as a workaround.

**Comment by tn4799** [comment] 2024-01-09 21:02
Update was released today in the modhub. Now the problem should be fixed.

**Closed as completed by tn4799** 2024-01-09 21:02 UTC
Labels: bug, Fixed in next update, Workaround available

**Comment by DeeDeeRanged** [comment] 2024-01-12 15:32
Sorry for late reply. A great thank you for the fix. It works now as it should. :+1:

**Comment by tn4799** [comment] 2024-01-12 15:58
No problem. 
The mistake was on my side. I didnt test it properly which lead to the bug
